### ISSUE TITLE
Supporting events over a date range

### ISSUE THREAD

**Issue by filipemir** [mfix22/calendarx#10]
Hi! For my use case I need to be add some support for multiday events. I don't believe these are currently supported (please correct me if I'm just completely missing it). I can address it from our end, but I was wondering if there is appetite for adding this support to the library. If so, I may see if I can curve out the time to submit a PR instead of baking the logic in our client.

From my quick glance of the source code it appears that calendarx transforms an array of events into a map of dates to an array of events happening on that day. Then each day checks for events at its respective key. In principle, we could just extend that to accommodate ranges but the memory footprint seems unnecessarily large for events that last many days. Maybe having a function that compares each date against a sorted set of events, checking whether it's in any date range that starts before or on that date, and then caching/memoizing the returned value would be a more efficient approach? Alternatively, I think we could keep the current approach but only populate the map one view at a time and refresh it when switching months, such that at most the map would have as many entries as there are days visible. I'm fine with either approach but I've only briefly glanced at the code, so any thoughts are appreciated

**Comment by mfix22** [comment]
I think this is _definitely_ a valid feature that we _should_ support. I appreciate the thorough idea too! I want to think more about how we can easily integrate it into the current system. Will post more thoughts soon 👍

**Comment by filipemir** [comment]
Cool. Let me know. If we have a path forward, I can put up a PR early next week
