### ISSUE TITLE
Include sourcemap file into npm package

### ISSUE THREAD

**Issue by gbiryukov** [mfix22/calendarx#14]
Thanks for awesome library!

Can you either include sourcemap file into npm package either remove `//# sourceMappingURL=calendarx.js.map` comment from `lib/calendarx.js`?

By publishing sourcemaps you allows people to use tools like `source-map-loader` and have clean error stacktraces

**Comment by mfix22** [comment]
@gbiryukov thanks for bringing this up! I hadn't noticed. I just republished this with source map files included as `calendarx@next` (`v1.2.1-0`). Can you try it out and confirm it is working for you? 🙂

**Comment by gbiryukov** [comment]
installed `v1.2.1-0` but unfortunately `.map` file is still missing. 
files published into npm can be controlled via `files` section of `package.json`. i.e. like this:
```
"files": [
  "/dist"
]
```

**Comment by mfix22** [comment]
Oops! Duh. You're right. Should be working in the latest release (https://unpkg.com/calendarx@1.2.1-1/dist/calendarx.js.map)

**Comment by mfix22** [comment]
Closing this, please let me know if you run into issue again — I will address them ASAP!

**Comment by gbiryukov** [comment]
now works great, thanks!
