### ISSUE TITLE
How do events render?

### ISSUE THREAD

**Issue by arecvlohe** [mfix22/calendarx#8]
@mfix22 Cool library! I just have a question about how events are rendered. When I open the codesandbox I would expect an event to render on the 1st (the example birthday event). But nothing appears to show.

<a href="https://cl.ly/1a23b588cdcc" target="_blank"><img src="https://d3r69eeiwn2k86.cloudfront.net/items/1b3c0t1M0y3i282e2M18/Screen%20Shot%202019-04-30%20at%203.26.40%20PM.png" style="display: block;height: auto;width: 100%;"/></a>

I suppose I need to modify event styles for events to render properly.

**Comment by arecvlohe** [comment]
I see you are passing it into Event which accepts children. Never mind!

**Comment by mfix22** [comment]
Thanks for posting! Let me know if there is anything else I can help with 🙏
