### ISSUE TITLE
TS declaration file

### ISSUE THREAD

**Issue by filipemir** [mfix22/calendarx#9]
Hello! Thanks for this library. It's saved me a ton of time already. I'm integrating it into a Typescript codebase. Is there any interest in integrating a Typescript declaration file into the repo? If so, I can submit a PR with an adapted version of the declaration file we're using on our end. Lemme know

**Comment by mfix22** [comment]
I'm glad it has helped! Absolutely — that would be amazing 🙌

**Comment by filipemir** [comment]
Cool. I'll send it over soon

**Comment by filipemir** [comment]
I'm having some difficulties getting it to work as a separate index.d.ts file. I'll loop back around to this, in the meantime, here's what I'm using, if anyone else out there needs it: 
```
declare module "calendarx" {
    import React from "react";
    import moment from "moment";

    type DateLike = Date | string | number | moment.Moment;
    type DateUnit = "year" | "month" | "week" | "day";
    type WeekdayNum = 0 | 1 | 2 | 3 | 4 | 5 | 6;

    interface BaseEvent {
        date: DateLike;
    }

    export interface CalendarxEvent extends BaseEvent {
        [key: string]: any;
    }

    export interface CalendarxDay {
        date: Date;
        events: CalendarxEvent[];
        isToday: boolean;
        isSame: (unit: DateUnit) => boolean;
    }

    export interface CalendarxChildrenProps {
        days: CalendarxDay[][];
        date: Date;
        view: DateUnit;
        jump: (n: number, units: DateUnit) => void;
        goToNext: () => void;
        goToPrev: () => void;
        goToToday: () => void;
        goToDate: (date: DateLike) => void;
        headers: { title: string; day: number }[];
    }

    export interface CalendarxProps {
        children?: React.SFC<CalendarxChildrenProps>;
        date?: DateLike;
        initialDate?: DateLike;
        initialNumDays?: number;
        numDays?: number;
        events?: CalendarxEvent[];
        weekStartsOn?: WeekdayNum;
        headers?: string[];
        render?: any;
    }

    const Calendar: React.FunctionComponent<CalendarxProps> & {
        useCalendar: (props: CalendarxProps) => CalendarxChildrenProps;
    };

    export default Calendar;
    export function useCalendar(props?: CalendarxProps): CalendarxChildrenProps;
}
```

**Comment by mfix22** [comment]
@filipemir you should checkout this section of `microbundle`'s docs on using it with TypeScript declarations: 
https://github.com/developit/microbundle#specifying-builds-in-packagejson

**Comment by filipemir** [comment]
I believe that would be helpful if the source code was TS. In that case, it could just generate the typings and dump them where instructed.

**Comment by mfix22** [comment]
Ahhh I see.

**Comment by mfix22** [comment]
Ahhh I see. @filipemir do you think it would be worth rewriting the package in TypeScript? 🙂

**Comment by filipemir** [comment]
I mean: I love TS but... probably not. TS adds a good amount of verbosity
that I think is only worth it for larger codebases. Unless you're looking
for a reason to pick it up, in which case: definitely go for it 🙂
Shouldn't be too too much work here. Otherwise, I think I'll just try to
spend a little longer in order to get the declaration file in shape to open
a PR on DefinitelyTyped.
